version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cache:/var/cache/nginx
      - ./files:/usr/share/nginx/html:ro
    environment:
      - NGINX_WORKER_PROCESSES=auto
    command: >
      /bin/bash -c "
      /usr/sbin/fcgiwrap -s unix:/var/run/fcgiwrap.socket &
      while [ ! -S /var/run/fcgiwrap.socket ]; do sleep 0.1; done &&
      chmod 666 /var/run/fcgiwrap.socket &&
      nginx -g 'daemon off;'"
